config/routes.rb
App::Application.routes.draw do

  resources :departments
  resources :businessunits
  resources :calendar
  devise_for :users
  resources :policies
  resources :dashboards

  root :to => 'dashboards#index'

end

app/models/policy.rb
class Policy < ActiveRecord::Base
	belongs_to :user
  attr_accessible :p_code, :p_description, :p_name, :p_objective, :p_scope , :attach , :businessunit_id 
  has_attached_file :attach
  belongs_to :businessunits
  belongs_to :documents
end

app/controllers/policies_controller.rb
class PoliciesController < ApplicationController
  # GET /policies
  # GET /policies.json
  def index
    @policies = Policy.all

   respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @policies }
    end
  end

  # GET /policies/1
  # GET /policies/1.json
  def show
    @policy = Policy.find(params[:id])
    

    respond_to do |format|
      format.html # show.html.erb
      format.pdf do
        pdf = PoliciesPdf.new(@policy)
        send_data pdf.render , filename: "#{@policy.p_name}.pdf", type: "application/pdf" , disposition: "inline"
      end
    end
  end

  # GET /policies/new
  # GET /policies/new.json
  def new
    @policy = Policy.new
    @businessunit = Businessunit.find(:all)
    @document = Document.find(:all)

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @policy }
    end
  end

  # GET /policies/1/edit
  def edit
    @policy = Policy.find(params[:id])
    @businessunit = Businessunit.find(:all)
    @document = Document.find(:all)
  end

  # POST /policies
  # POST /policies.json
  def create
    @policy = Policy.new(params[:policy])

    respond_to do |format|
      if @policy.save
        format.html { redirect_to @policy, notice: 'Policy was successfully created.' }
        format.json { render json: @policy, status: :created, location: @policy }
      else
        format.html { render action: "new" }
        format.json { render json: @policy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /policies/1
  # PUT /policies/1.json
  def update
    @policy = Policy.find(params[:id])

    respond_to do |format|
      if @policy.update_attributes(params[:policy])
        format.html { redirect_to @policy, notice: 'Policy was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @policy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /policies/1
  # DELETE /policies/1.json
  def destroy
    @policy = Policy.find(params[:id])
    @policy.destroy

    respond_to do |format|
      format.html { redirect_to policies_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/policies_helper.rb
module PoliciesHelper
end

app/views/policies/_form.html.erb
<%= form_for(@policy) do |f| %>
<% if @policy.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@policy.errors.count, "error") %> prohibited this policy from being saved:</h2>

  <ul>
    <% @policy.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>
<div class="span11 offset well">
  <div class="form-horizontal">
    <div class="accordion " id="accordion2">
      <div class="accordion-group">
        <div class="accordion-heading">
          <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
            New Policy 
          </a>
        </div>
        <div id="collapseOne" class="accordion-body collapse in">
          <div class="accordion-inner">
            <div class="control-group">
              <%= f.label "Policy Name" %>
              <%= f.text_field :p_name %>
            </div>
            <div class="control-group">
              <%= f.label "Policy Code" %>
              <%= f.text_field :p_code %>
            </div>
            <div class="control-group">

              <%= f.label "Business Units" %>
              <%= f.collection_select :businessunit_id , @businessunit, :id ,:b_name %>
            </div>
          </div>
        </div>
      </div>
      <div class="accordion-group">
        <div class="accordion-heading">
          <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseTwo">
            Scope and Objective
          </a>
        </div>
        <div id="collapseTwo" class="accordion-body collapse">
          <div class="accordion-inner">
            <div class="control-group">
              <%= f.label "Policy Scope" %>
              <%= f.text_area :p_scope  , :rows => 5, :cols => 500  %>
            </div>
            <div class="control-group">
              <%= f.label "Policy Objective" %>
              <%= f.text_area :p_objective , :rows => 5, :cols => 500 %>
            </div>
            <div class="control-group">
              <%= f.label "Policy Description" %>
              <%= f.text_area :p_description  , :rows => 5, :cols => 500 %>
            </div>
          </div>
        </div>
      </div>
      <div class="accordion-group">
        <div class="accordion-heading">
          <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapsethree">
            Document Control
          </a>
        </div>
        <div id="collapsethree" class="accordion-body collapse">
          <div class="accordion-inner">
            <div class="control-group">
              <b> Document Title </b><br/>
            </div>
            <div class="control-group">
              <b> Attachment </b><br/>
              <%= f.file_field :attach %>
            </div>
          </div>
        </div>
      </div>
      <div class="accordion-group">
        <div class="accordion-heading">
          <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapsefour">
            Governance Risk and Compliance
          </a>
        </div>
        <div id="collapsefour" class="accordion-body collapse">
          <div class="accordion-inner">
            <p>Governance Risk and Compliance</p>
          </div>
        </div>
      </div>
      <div class="accordion-group">
        <div class="accordion-heading">
          <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapsefive">
            Approval , Review and  Distribution
          </a>
        </div>
        <div id="collapsefive" class="accordion-body collapse">
          <div class="accordion-inner">
            <p>Approval , Review and  Distribution</p>
          </div>
        </div>
      </div>
    </div>
  </div>
  <br>
  <div>
    <%= f.submit 'Create Policy', :class =>  "pure-button pure-button-primary"%>
    <%= link_to 'Cancel', policies_path , :class => "pure-button pure-button-primary"%>
  </div>
  <% end %>
</div>

app/views/policies/edit.html.erb
<html>
<head>
	<title></title>
</head>
<body>
	<div id="header">
		<div><img src="/images/fixnix.png"></div>
	</div>
	<div id="main-wrap">
		<div id="sidebar">
			<%= render :partial => "layouts/menu" %>
		</div>
		<div id="content-wrap">
			<div class="span12 offset well"> 
				<h1>Editing policy</h1>

				<%= render 'form' %>
			</div>
		</div>
	</div>
	<!-- 	<div id="footer">Footer</div> -->

</body>
</html>

app/views/policies/index.html.erb
<html>
<head>
    <title></title>
</head>
<body>
    <div id="header">
        <div><img src="/images/fixnix.png"></div>
    </div>
    <div id="main-wrap">
        <div id="sidebar">
            <%= render :partial => "layouts/menu" %>
        </div>
        <div id="content-wrap">
            <div class="sapn10 offset well">
                <div class="tabbable">
                    <ul class="nav nav-tabs">
                        <li class="active"><a href="#Policy" data-toggle="tab">Policy</a></li>
                        <li><a href="#EP" data-toggle="tab">Existing Policies</a></li>
                    </ul>
                    <div class="tab-content">
                        <div id="Policy" class="tab-pane active">
                            <table class="table table-bordered">
                                <tr>
                                   <th>Code</th>
                                   <th>Policy</th>

                               </tr>
                               <% @policies.each do |policy| %>
                               <tr>
                                <td><%= policy.p_code %></td>
                                <td><%= policy.p_name %></td>
                                <td><%= link_to 'Show', policy %></td>
                                <!-- <td><%= link_to 'Edit', edit_policy_path(policy) %></td> -->
                                <td><%= link_to 'Destroy', policy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                            </tr>
                            <% end %>
                        </table>
                        <br />
                        <%= link_to 'New Policy', new_policy_path , :class => "pure-button pure-button-primary" %>
                    </div>
                    <div id="EP" class="tab-pane">
                        <h4>Existing Policies</h4>
                        <p> Coming Soon ...</p>
                    </div>
                </div><!-- /.tab-content -->
            </div><!-- /.tabbable -->
        </div>
    </div>
</div>
<!-- <div id="footer">Footer</div> -->
</body>
</html>

app/views/policies/new.html.erb
<html>
<head>
	<title></title>
</head>
<body>
	<div id="header">
		<div><img src="/images/fixnix.png"></div>
	</div>
	<div id="main-wrap">
		<div id="sidebar">
			<%= render :partial => "layouts/menu" %>
		</div>
		<div id="content-wrap">

			<%= render 'form' %>
			<br>

		</div>
	</div>
	<!-- <div id="footer">Footer</div> -->
</body>
</html>

app/views/policies/show.html.erb
<html>
<head>
  <title></title>
</head>
<body>
  <div id="header">
    <div><img src="/images/fixnix.png"></div>
  </div>
  <div id="main-wrap">
    <div id="sidebar">
      <%= render :partial => "layouts/menu" %>
    </div>
    <div id="content-wrap">
      <p id="notice"><%= notice %></p>

      <p>
        <b>Policy Name</b>
        <%= @policy.p_name %>
      </p>

      <p>
        <b>Policy Code</b>
        <%= @policy.p_code %>
      </p>

      <p>
        <b>Policy Scope</b>
        <%= @policy.p_scope %>
      </p>

      <p>
        <b>Policy Objective</b>
        <%= @policy.p_objective %>
      </p>

      <p>
        <b>Policy Description</b>
        <%= @policy.p_description %>
      </p>
      <p>
        <a href="<%= @policy.attach.url %> ">
         <b> File attached </b></a>
       </p>
       <%= link_to "Show Report", policy_path(@policy, :format => "pdf") , :class => "pure-button pure-button-primary"  %>
       <%= link_to 'Edit', edit_policy_path(@policy) , :class => "pure-button pure-button-primary"  %> 
       <%= link_to 'New Policy', new_policy_path , :class => "pure-button pure-button-primary"  %>

     </div>
   </div>
   <!--   <div id="footer">Footer</div> -->

 </body>
 </html>